name: app-ocean-sensation
services:
- name: web
  git:
    repo_clone_url: https://github.com/jackiebanh/engineers-api.git
    branch: main
  routes:
  - path: /
  envs:
  - key: KEY
    value: VALUE
databases:
- name: db-mongo-ocean-sensation
  engine: MONGODB
  production: true
  cluster_name: cluster-ocean-sensation
  db_name: db-mongo-ocean-sensation
