alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
databases:
- engine: MONGO
  production: true
  cluster_name: db-cluster
  db_name: db
name: engineers-api
region: sgp
services:
- environment_slug: node-js
  envs:
  - key: DATABASE_URL
    scope: RUN_TIME
    value: ${db.DATABASE_URL}
  github:
    branch: main
    deploy_on_push: true
    repo: jackiebanh/engineers-api
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xs
  name: engineers-api
  routes:
  - path: /
  run_command: npm start
  source_dir: /app